version: '2'
services:
  stiger-admin-db:
    image: mysql:5.7.29
    container_name: mysql13306
    hostname: mysql13306
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    # 将./database/my.cnf拷贝至映射出来的conf.d目录下
    # 将./database/sql.sql拷贝到映射出来的docker-entrypoint-initdb.d目录下
    volumes:
      - "/Users/snake/docker/container/mysql/5.7.29/mysql13306/data:/var/lib/mysql"
      - "/Users/snake/docker/container/mysql/5.7.29/mysql13306/conf.d:/etc/mysql/conf.d"
      - "/Users/snake/docker/container/mysql/5.7.29/mysql13306/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
  stiger-admin-redis:
    image: redis:5.0.8
    container_name: redis16379
    hostname: redis16379
    ports:
      - 16379:6379
    volumes:
      - "/Users/snake/docker/container/redis/5.0.8/etc:/usr/local/etc/redis"
      - "/Users/snake/docker/container/redis/5.0.8/data:/data"
  stiger-admin-ui:
    build:
      context: ./star-tiger-admin-ui
      args:
        profile: docker
    image: stiger-admin-ui
    container_name: stigeradmin19999
    ports:
      - 19999:9999
