version: '2'
services:
  stiger-admin-db:
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    container_name: mysql13306
    image: stiger-admin-db
    hostname: mysql13306
    ports:
      - 13306:3306
    volumes:
      - "/Users/snake/docker/container/mysql/5.7.29/mysql13306:/var/lib/mysql"
  stiger-admin-redis:
    image: redis:5.0.8
    hostname: redis16379
    ports:
      - 16379:6379
    container_name: redis16379
    volumes:
      - "/Users/snake/docker/container/redis/5.0.8/etc:/usr/local/etc/redis"
      - "/Users/snake/docker/container/redis/5.0.8/data:/data"
  stiger-admin-ui:
    build:
      context: ./star-tiger-admin-ui
#      args:
#        jar_file: ./target/StarTigerAdminUi.jar
#        spring_prifiles_active: docker
    restart: always
    ports:
      - 19999:9999
#    links:
#      - "mysql13306:mysql13306"
#      - "redis16379:redis16379"
    container_name: stigeradmin19999
    image: stiger-admin-ui
