version: '2'
services:
  stiger-admin-db-master:
    build:
      context: ./database
    image: stiger-admin-mysql
    container_name: mysql13306
    hostname: mysql13306
    ports:
      - 13306:3306
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    # 将./database/my.cnf拷贝至映射出来的conf.d目录下
    # 将./database/sql下的初始化脚本拷贝至映射出来的init目录下
    volumes:
      - "/Users/snake/docker/container/mysql/5.7.29/mysql13306/data:/var/lib/mysql"
      - "/Users/snake/docker/container/mysql/5.7.29/mysql13306/conf.d:/etc/mysql/conf.d"
      - "/Users/snake/docker/container/mysql/5.7.29/mysql13306/sql:/init"
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
  stiger-admin-db-slave1:
    image: stiger-admin-mysql
    container_name: mysql23306
    hostname: mysql23306
    ports:
      - 23306:3306
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    # 将./database/my.cnf拷贝至映射出来的conf.d目录下，并将server-id改成2
    volumes:
      - "/Users/snake/docker/container/mysql/5.7.29/mysql23306/data:/var/lib/mysql"
      - "/Users/snake/docker/container/mysql/5.7.29/mysql23306/conf.d:/etc/mysql/conf.d"
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
  stiger-admin-redis:
    image: redis:5.0.8
    container_name: redis16379
    hostname: redis16379
    ports:
      - 16379:6379
    volumes:
      - "/Users/snake/docker/container/redis/5.0.8/etc:/usr/local/etc/redis"
      - "/Users/snake/docker/container/redis/5.0.8/data:/data"
  stiger-admin-ui:
    build:
      context: ./star-tiger-admin-ui
      args:
        ACTIVE_PROFILE: docker
    image: stiger-admin-ui
    container_name: stigeradmin19999
    ports:
      - 19999:9999
  stiger-admin-ui-dynamic:
    build:
      context: ./star-tiger-admin-ui
      args:
        ACTIVE_PROFILE: dockerdynamic
    image: stiger-admin-ui-dynamic
    container_name: stigeradmin29999
    ports:
      - 29999:9999
