spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:13306/stigeradmin?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8
      username: root
      password: 123456
    slave1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:23306/stigeradmin?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8
      username: root
      password: 123456
  redis:
    host: localhost
    port: 16379
  thymeleaf:
    cache: false
  cache:
    type: redis
    redis:
      time-to-live: 1m
  session:
    store-type: redis
server:
  port: 9999
  servlet:
    session:
      timeout: 30M
stiger:
  admin:
    web:
      security:
        remember-me-key: stiger-admin